version: '3.8'

services:

  #1. Aplicación
  web: 
    build: . #TO-DO: Crear el Dockerfile para construir la imagen web
    ports:
      - "8080:8080"

  #2. Base de datos
  db: 
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWD}
      MYSQL_DATABASE: ${DB}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_USER_PASSWD}
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
    - "3307:3306"

  #3. Herramienta de administración de la BD
  adminer: 
    image: adminer
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      - db

  #4. Memoria caché
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  #5. Servidor de correos
  mailpit:
    image: axllent/mailpit
    ports:
      - "8025:8025" #Web UI (http://localhost:8025)
      - "1025:1025" #SMPT



volumes:
  mysql_data:
